"use client";

import Link from "next/link";
import { FormEvent, ReactNode, useState } from "react";
import { ArrowRight, BriefcaseBusiness, Camera, Car, Check, ChevronDown, CircleCheck, Flower2, Hammer, HeartHandshake, House, Menu, Paintbrush, Scissors, Sparkles, Store, Utensils, Wrench, X } from "lucide-react";
import { packages, projects } from "@/lib/data";

const nav = [["Home", "#home"], ["Services", "#services"], ["Pricing", "#pricing"], ["Portfolio", "#portfolio"], ["How It Works", "#process"], ["FAQ", "#faq"], ["Contact", "#contact"]];
const Button = ({ href, children, secondary = false }: { href: string; children: ReactNode; secondary?: boolean }) => <a href={href} className={`button ${secondary ? "secondary" : "primary"}`}>{children}<ArrowRight size={17} aria-hidden /></a>;
const Kicker = ({ children }: { children: ReactNode }) => <p className="kicker">{children}</p>;

export function Header() {
  const [open, setOpen] = useState(false);
  return <header className="header"><div className="container nav-wrap"><a className="logo" href="#home" aria-label="SiteSimple home"><span>S</span>SiteSimple</a><nav className="desktop-nav" aria-label="Main navigation">{nav.map(([label, href]) => <a key={href} href={href}>{label}</a>)}</nav><a className="button primary header-cta" href="#contact">Get My Website</a><button className="menu-button" onClick={() => setOpen(!open)} aria-expanded={open} aria-controls="mobile-menu" aria-label="Toggle menu">{open ? <X /> : <Menu />}</button></div>{open && <nav id="mobile-menu" className="mobile-menu" aria-label="Mobile navigation">{nav.map(([label, href]) => <a key={href} href={href} onClick={() => setOpen(false)}>{label}</a>)}<a className="button primary" href="#contact" onClick={() => setOpen(false)}>Get My Website</a></nav>}</header>;
}

export function Hero() {
  return <section className="hero" id="home"><div className="container hero-grid"><div><div className="eyebrow"><span />Websites for small business</div><h1>Professional Websites.<br/><em>Made Simple.</em></h1><p className="hero-copy">You run your business. We’ll handle the website. Get a modern, professional website without spending thousands on an agency or wasting hours trying to build it yourself.</p><div className="button-row"><Button href="#contact">Get My Website</Button><Button href="#pricing" secondary>See Pricing</Button></div><p className="trust"><Check /> Done-for-you <b>•</b> Mobile-friendly <b>•</b> No tech headaches</p></div><HeroVisual /></div></section>;
}

function HeroVisual() { return <div className="hero-visual" aria-label="Original example of a landscaping business website on desktop and mobile"><div className="browser"><div className="browser-bar"><i/><i/><i/><span>greenwaylandscapes.com</span></div><div className="mock-nav"><b><Flower2 size={17}/>Greenway</b><small>Services&nbsp;&nbsp; About&nbsp;&nbsp; Contact</small></div><div className="mock-hero"><small>LOCAL LAWN & LANDSCAPE</small><strong>Outdoor spaces,<br/>beautifully kept.</strong><p>Reliable care for lawns you love coming home to.</p><button>Get a free quote</button></div><div className="mock-stats"><b>Weekly care</b><b>Local team</b><b>Easy quotes</b></div></div><div className="phone"><div className="phone-notch"/><div className="mini-brand"><Flower2 size={14}/> Greenway</div><div className="mini-photo"><small>YOUR LOCAL LAWN TEAM</small><b>Love your<br/>outdoors.</b><i>Get a free quote</i></div></div><div className="floating-note"><CircleCheck/><span><b>Built to get calls</b><small>Clear, focused, ready to work</small></span></div></div> }

export function ProblemComparison() { const diy = ["You build everything", "You choose the layout", "You configure the website", "You troubleshoot problems", "You spend your time"], us = ["We build it", "We design it", "We configure it", "We launch it", "You run your business"]; return <section className="section warm"><div className="container problem-grid"><div><Kicker>THE DIY REALITY</Kicker><h2>You could build it yourself.<br/><em>But should you have to?</em></h2><p>Website builders give you the tools—but you still have to choose templates, design pages, write content, configure forms, optimize mobile layouts, connect domains, figure out SEO, and troubleshoot problems.</p><div className="highlight"><Sparkles/><p><b>SiteSimple handles it for you.</b><br/><span>We turn your business details into a professional website, so you can stay focused on the work that pays.</span></p></div></div><div className="comparison"><div><small>DIY WEBSITE BUILDER</small>{diy.map(x=><p key={x}><X/> {x}</p>)}</div><div className="compare-us"><span className="mini-logo">S</span><small>WITH SITESIMPLE</small>{us.map(x=><p key={x}><Check/> {x}</p>)}</div></div></div></section> }

const serviceItems = [
  [House, "Landing Pages", "Simple, professional online presence for businesses that need to get online quickly."],
  [BriefcaseBusiness, "Small Business Websites", "Complete professional websites for established local businesses."],
  [Paintbrush, "Website Redesigns", "Modernize an outdated or DIY website with a clearer, more polished experience."],
  [Wrench, "Website Care", "Ongoing support, content updates, monitoring, and maintenance."],
] as const;
export function Services() { return <section id="services" className="section"><div className="container"><div className="section-head"><div><Kicker>WHAT WE DO</Kicker><h2>Everything you need.<br/><em>Nothing you don’t.</em></h2></div><p>Simple, focused web design for businesses that need to look professional and make it easy for customers to take the next step.</p></div><div className="service-grid">{serviceItems.map(([Icon,title,copy],i)=><article className="service-card" key={title}><span className="number">0{i+1}</span><div className="icon-box"><Icon/></div><h3>{title}</h3><p>{copy}</p><a href="#contact">Learn more <ArrowRight/></a></article>)}</div></div></section> }

export function Pricing() { return <section id="pricing" className="section navy"><div className="container"><div className="center-head"><Kicker>SIMPLE, UPFRONT PRICING</Kicker><h2>Choose the website that<br/><em>fits your business.</em></h2><p>No confusing proposals. No mystery costs. Just a clear path to getting online.</p></div><div className="pricing-grid">{packages.map(p=><article key={p.name} className={`price-card ${p.popular ? "popular" : ""}`}>{p.popular && <div className="popular-label">MOST POPULAR</div>}<h3>{p.name}</h3><p>{p.blurb}</p><strong className="price">{p.price}</strong><small>one-time project price</small><a href={`#contact`} className={`button ${p.popular ? "primary" : "secondary"}`} data-package={p.name}>{p.cta}<ArrowRight size={17}/></a><div className="features">{p.features.map(f=><span key={f}><Check/> {f}</span>)}</div></article>)}</div><p className="pricing-note"><CircleCheck/> No surprise agency bills. Know what you’re paying before we start.</p></div></section> }

export function WebsiteCare() { return <section className="care"><div className="container care-card"><div className="care-title"><div className="icon-box"><HeartHandshake/></div><div><span className="pill">OPTIONAL ADD-ON</span><h2>Keep Your Website<br/><em>Taken Care Of.</em></h2></div></div><div className="care-content"><p className="price"><b>$39</b>/month</p><p>Keep your website current and working smoothly without adding another task to your list.</p><div className="care-list">{["Website support", "Small text updates", "Photo updates", "Basic maintenance", "Website monitoring"].map(x=><span key={x}><Check/> {x}</span>)}</div><Button href="#contact">Add Website Care</Button></div></div></section> }

export function WebsiteRescue() { const improvements=["Professional redesign", "Better mobile experience", "Cleaner layout", "Stronger calls to action", "Contact improvements", "Visual cleanup", "Basic SEO improvements"]; return <section className="section rescue"><div className="container rescue-grid"><div><Kicker>DIY WEBSITE RESCUE</Kicker><h2>Already built a website<br/>but hate it? <em>We’ll fix it.</em></h2><p>You may not need to start over. We can improve the website you already have, keeping what works and cleaning up what doesn’t.</p><div className="rescue-price"><b>Starting at $249</b><span>Based on the scope of your existing site</span></div><Button href="#contact">Fix My Website</Button></div><div className="rescue-list">{improvements.map((x,i)=><div key={x}><span>0{i+1}</span><b>{x}</b><Check/></div>)}</div></div></section> }

export function HowItWorks() { const steps=[["Tell Us About Your Business","Complete a simple project questionnaire so we understand your business and goals."],["We Build It","SiteSimple handles the design, content layout, and technical setup."],["You Approve It","Review your website and request the revision rounds included with your package."],["We Launch It","We connect your domain, complete final checks, and launch your new website."]]; return <section id="process" className="section process"><div className="container"><div className="center-head"><Kicker>HOW IT WORKS</Kicker><h2>From idea to online in<br/><em>four simple steps.</em></h2></div><div className="steps">{steps.map(([title,copy],i)=><article key={title}><span>{i+1}</span><h3>{title}</h3><p>{copy}</p>{i<3&&<ArrowRight className="step-arrow"/>}</article>)}</div><p className="process-line">No coding. <b>•</b> No templates to figure out. <b>•</b> No tech headaches.</p></div></section> }

export function Portfolio() { return <section id="portfolio" className="section portfolio"><div className="container"><div className="section-head"><div><Kicker>OUR WORK</Kicker><h2>Made for the businesses<br/><em>that keep things moving.</em></h2></div><div><p>Original demo concepts created to show what we can build for businesses like yours.</p><small>Concept work—not client projects.</small></div></div><div className="portfolio-grid">{projects.map((p)=><article className="project" key={p.name}><div className={`project-preview ${p.theme}`}><div className="project-browser"><div className="dots">•••</div><nav><b>{p.name}</b><small>Services&nbsp;&nbsp; About&nbsp;&nbsp; Contact</small></nav><div><small>{p.category.toUpperCase()}</small><h3>{p.eyebrow}</h3><button>{p.action}</button></div></div><div className="project-phone"><span/><b>{p.name.split(" ")[0]}</b><p>{p.eyebrow}</p><i>{p.action}</i></div></div><div className="project-info"><span className="pill">DEMO CONCEPT</span><small>{p.category}</small><h3>{p.name}</h3><p>{p.description}</p><div>{p.services.map(s=><span key={s}>{s}</span>)}</div></div></article>)}</div><div className="portfolio-cta"><p><b>Like what you see?</b> Let’s build something that feels like your business.</p><Button href="#contact" secondary>Start Your Project</Button></div></div></section> }

const industries = [[Hammer,"Contractors"],[Sparkles,"Cleaning"],[Flower2,"Landscaping"],[Car,"Automotive"],[Scissors,"Beauty"],[Camera,"Photography"],[House,"Real Estate"],[HeartHandshake,"Childcare"],[BriefcaseBusiness,"Coaching"],[Utensils,"Restaurants"],[Store,"Local Services"],[HeartHandshake,"Nonprofits"]] as const;
export function Industries() { return <section className="section"><div className="container industries-wrap"><div><Kicker>WHO WE HELP</Kicker><h2>Built for<br/><em>Small Business.</em></h2><p>Whether you’re starting something new or finally ready to upgrade your online presence, we’ll make getting a professional website simple.</p><Button href="#contact">Let’s Talk About Your Site</Button></div><div className="industry-grid">{industries.map(([Icon,name])=><div key={name}><Icon/><span>{name}</span></div>)}</div></div></section> }

const faqs = [
  ["How long does a website take?", "Turnaround depends on your package, project scope, and how quickly you provide the content and feedback we need. We’ll confirm a realistic timeline before work begins."],
  ["Do I need to know anything about websites?", "No. Tell us about your business and goals; we’ll guide you through the decisions and handle the technical details."],
  ["Do I need my own domain?", "If you already own one, we can connect it. If not, we’ll guide you through purchasing one in your name."],
  ["Is hosting included?", "Hosting is not included indefinitely in the one-time project price. We’ll recommend an appropriate hosting option and clearly explain any ongoing cost before launch."],
  ["Can you redesign my existing website?", "Yes. We can refresh an existing website or recommend a rebuild when that is the more practical choice."],
  ["Can I update my website later?", "Yes. You can request future updates as needed, or choose the optional Website Care plan for ongoing support and small updates."],
  ["Do you build online stores?", "Ecommerce projects require a custom quote because product counts, payments, shipping, and other requirements vary."],
  ["Do you build custom apps?", "Advanced applications and custom functionality are outside the standard packages, but can be discussed and quoted separately."],
  ["How does payment work?", "Projects require a 50% deposit before work begins, with the remaining balance due before the website launches."],
  ["Are there monthly fees?", "Website Care is optional. Domain registration, hosting, or third-party services may still have separate recurring fees where applicable."],
];
export function FAQ() { return <section id="faq" className="section faq"><div className="container faq-grid"><div><Kicker>QUESTIONS, ANSWERED</Kicker><h2>Good questions.<br/><em>Simple answers.</em></h2><p>Still wondering about something?</p><a href="#contact">Send us your question <ArrowRight/></a></div><div className="accordion">{faqs.map(([q,a],i)=><details key={q} open={i===0}><summary>{q}<ChevronDown/></summary><p>{a}</p></details>)}</div></div></section> }

export function About() { return <section className="section about"><div className="container about-card"><div><Kicker>WHY SITESIMPLE</Kicker><h2>There should be a better option.</h2></div><div><p className="lead">Small businesses shouldn’t have to choose between an expensive agency and figuring everything out themselves.</p><p>SiteSimple is the middle option: professional, done-for-you websites at straightforward prices. We keep the process clear, the design focused, and the technical headaches off your plate.</p><p className="signature"><span>S</span><b>Professional websites.<br/><em>Made simple.</em></b></p></div></div></section> }

export function Contact() { return <section id="contact" className="section contact"><div className="container contact-grid"><div><Kicker>LET’S GET STARTED</Kicker><h2>Tell us about<br/><em>your business.</em></h2><p>Complete the form and we’ll review your project details. No confusing tech talk and no pressure—just a clear conversation about what you need.</p><div className="contact-points">{["Clear, straightforward pricing", "A process built around your schedule", "Professional design without the agency overhead"].map(x=><span key={x}><Check/>{x}</span>)}</div><div className="expect"><b>What happens next?</b><p>We’ll review your inquiry and follow up to discuss fit, scope, and next steps. Your project only begins after you approve the details.</p></div></div><ContactForm/></div></section> }

function ContactForm() {
  const [status,setStatus]=useState<"idle"|"loading"|"success"|"error">("idle"); const [message,setMessage]=useState("");
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setStatus("loading");setMessage("");const form=e.currentTarget;const payload=Object.fromEntries(new FormData(form));try{const response=await fetch("/api/inquiry",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const data=await response.json();if(!response.ok)throw new Error(data.error);setStatus("success");form.reset()}catch(error){setStatus("error");setMessage(error instanceof Error?error.message:"Something went wrong. Please try again.")}}
  if(status==="success") return <div className="form-card form-success" role="status"><CircleCheck/><h3>Thanks! Your inquiry is on its way.</h3><p>We’ll review your project details and follow up about next steps.</p><button className="button secondary" onClick={()=>setStatus("idle")}>Send another inquiry</button></div>;
  return <form className="form-card" onSubmit={submit}><div className="form-heading"><span>01</span><div><h3>Project inquiry</h3><p>Fields marked * are required</p></div></div><div className="form-grid"><Field label="Your name *" name="name" placeholder="Jordan Smith"/><Field label="Business name *" name="businessName" placeholder="Your business"/><Field label="Email address *" name="email" type="email" placeholder="you@business.com"/><Field label="Phone (optional)" name="phone" type="tel" placeholder="(555) 000-0000"/><Field label="Business type *" name="businessType" placeholder="e.g. Landscaping"/><Field label="Current website (optional)" name="currentWebsite" type="url" placeholder="https://"/><label>Package interested in *<select name="package" required defaultValue=""><option value="" disabled>Select a package</option>{packages.map(p=><option key={p.name}>{p.name} — {p.price}</option>)}<option>DIY Website Rescue — Starting at $249</option><option>Custom Project</option><option>Not Sure</option></select></label><label>Do you already own a domain? *<select name="domain" required defaultValue=""><option value="" disabled>Select an answer</option><option>Yes</option><option>No</option><option>Not sure</option></select></label></div><label>What does your business do? *<textarea name="description" required rows={3} placeholder="Tell us about your services and customers."/></label><label>What do you want your website to accomplish? *<textarea name="goal" required rows={3} placeholder="Get more calls, look more professional, show my work..."/></label><label>Anything else we should know?<textarea name="notes" rows={2} placeholder="Timelines, inspiration, questions, or other details."/></label>{status==="error"&&<p className="form-error" role="alert">{message}</p>}<button className="button primary submit" disabled={status==="loading"}>{status==="loading"?"Sending…":"Get My Website"}<ArrowRight/></button><p className="form-note">By submitting, you agree that SiteSimple may contact you about your inquiry.</p></form>
}
function Field({label,name,type="text",placeholder}:{label:string;name:string;type?:string;placeholder:string}){return <label>{label}<input name={name} type={type} placeholder={placeholder} required={label.includes("*")}/></label>}

export function FinalCTA() { return <section className="final-cta"><div className="container"><small>READY WHEN YOU ARE</small><h2>Your business deserves more<br/>than just a Facebook page.</h2><p>Get a professional website without the agency price or DIY headache.</p><Button href="#contact">Let’s Build Your Website</Button></div></section> }
export function Footer() { return <footer><div className="container footer-grid"><div><a className="logo light" href="#home"><span>S</span>SiteSimple</a><p>Professional Websites.<br/><em>Made Simple.</em></p><small>Done-for-you websites for small businesses.</small></div><div><b>Navigate</b>{nav.slice(1).map(([x,h])=><a href={h} key={x}>{x}</a>)}</div><div><b>Services</b><a href="#services">Landing Pages</a><a href="#services">Business Websites</a><a href="#services">Website Redesigns</a><a href="#services">Website Care</a></div><div><b>Legal</b><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link><span className="social-label">Social profiles coming soon</span></div></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} SiteSimple. All rights reserved.</span><span>Built for small business.</span></div></footer> }

export function LegalPage({title,children}:{title:string;children:ReactNode}) { return <><Header/><main className="legal container"><Kicker>SITESIMPLE</Kicker><h1>{title}</h1><p className="updated">Last updated August 14, 2026</p><div>{children}</div></main><Footer/></> }
